### ISSUE TITLE
All sample files have /nirs/aux/time and /nirs/data/time stored as 2D array

### ISSUE THREAD

**Issue by kdarti** [fNIRS/snirf-samples#12]
All sample files have /nirs/aux/time and /nirs/data/time stored as 2D array, but according to snirf spec it should be 1D array. Not a big thing, but e.g. mne-nirs [aux reading function](https://github.com/mne-tools/mne-nirs/blob/main/mne_nirs/io/snirf/_aux.py) fails due to this since it expects a 1D array.

**Comment by fangq** [comment]
This is an issue that I am aware of, but still haven't got a good fix.

the issue comes from the fact that the [minimum matlab data array dimensions is 2](https://www.mathworks.com/help/matlab/ref/double.ndims.html#:~:text=number%20of%20dimensions%20is%20always%20greater%20than%20or%20equal%20to%202), so there is no way one can tell if an Nx1 array is supposed to be 1D vector of length N, or a 2D array; similarly, it is also difficult to tell easyh5 [saveh5 function](https://github.com/NeuroJSON/easyh5/blob/master/saveh5.m) that an N x 1 x 1 array is 3 or higher dimensional because matlab `ndims()` function will always return 2.

**Comment by kdarti** [comment]
Ok, so if I understand you correctly, the issue isn't with actually writing a 1d array, but rather knowing when to write it as 1d array?

**Comment by fangq** [comment]
that's correct.

the source of this issue came from the design that my [savesnirf.m](https://github.com/NeuroJSON/jsnirfy/blob/master/savesnirf.m) function was built on top of a general-purpose HDF5 writer, `saveh5.m`. The SNIRF-specific settings must be somehow passed onto saveh5 to be reinforced - this is possible for data types, but for dimensions, I haven't found a way to let savesnirf.m to "inform" saveh5 such requirements.

one idea is to allow saveh5 to have a "schema" input so that such requirements can be propagated into, but I was hoping to find a less invasive solution.
